// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lk_logit_inv_cpp
NumericVector lk_logit_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_logit_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_logit_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_logistic_poly_cpp
NumericVector lk_logistic_poly_cpp(NumericVector p, int k);
RcppExport SEXP _linkfunctions7_lk_logistic_poly_cpp(SEXP pSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_logistic_poly_cpp(p, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_logit_fwd_cpp
NumericVector lk_logit_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_logit_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_logit_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_probit_fwd_cpp
NumericVector lk_probit_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_probit_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_probit_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_probit_inv_cpp
NumericVector lk_probit_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_probit_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_probit_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_cloglog_fwd_cpp
NumericVector lk_cloglog_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_cloglog_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_cloglog_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_cloglog_inv_cpp
NumericVector lk_cloglog_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_cloglog_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_cloglog_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_loglog_fwd_cpp
NumericVector lk_loglog_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_loglog_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_loglog_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_loglog_inv_cpp
NumericVector lk_loglog_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_loglog_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_loglog_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_cauchit_fwd_cpp
NumericVector lk_cauchit_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_cauchit_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_cauchit_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_cauchit_inv_cpp
NumericVector lk_cauchit_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_cauchit_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_cauchit_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_rhobit_fwd_cpp
NumericVector lk_rhobit_fwd_cpp(NumericVector theta, int k);
RcppExport SEXP _linkfunctions7_lk_rhobit_fwd_cpp(SEXP thetaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_rhobit_fwd_cpp(theta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_rhobit_inv_cpp
NumericVector lk_rhobit_inv_cpp(NumericVector eta, int k);
RcppExport SEXP _linkfunctions7_lk_rhobit_inv_cpp(SEXP etaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_rhobit_inv_cpp(eta, k));
    return rcpp_result_gen;
END_RCPP
}
// lk_softplus_fwd_cpp
NumericVector lk_softplus_fwd_cpp(NumericVector theta, double a, int k);
RcppExport SEXP _linkfunctions7_lk_softplus_fwd_cpp(SEXP thetaSEXP, SEXP aSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lk_softplus_fwd_cpp(theta, a, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_linkfunctions7_lk_logit_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_logit_inv_cpp, 2},
    {"_linkfunctions7_lk_logistic_poly_cpp", (DL_FUNC) &_linkfunctions7_lk_logistic_poly_cpp, 2},
    {"_linkfunctions7_lk_logit_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_logit_fwd_cpp, 2},
    {"_linkfunctions7_lk_probit_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_probit_fwd_cpp, 2},
    {"_linkfunctions7_lk_probit_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_probit_inv_cpp, 2},
    {"_linkfunctions7_lk_cloglog_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_cloglog_fwd_cpp, 2},
    {"_linkfunctions7_lk_cloglog_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_cloglog_inv_cpp, 2},
    {"_linkfunctions7_lk_loglog_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_loglog_fwd_cpp, 2},
    {"_linkfunctions7_lk_loglog_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_loglog_inv_cpp, 2},
    {"_linkfunctions7_lk_cauchit_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_cauchit_fwd_cpp, 2},
    {"_linkfunctions7_lk_cauchit_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_cauchit_inv_cpp, 2},
    {"_linkfunctions7_lk_rhobit_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_rhobit_fwd_cpp, 2},
    {"_linkfunctions7_lk_rhobit_inv_cpp", (DL_FUNC) &_linkfunctions7_lk_rhobit_inv_cpp, 2},
    {"_linkfunctions7_lk_softplus_fwd_cpp", (DL_FUNC) &_linkfunctions7_lk_softplus_fwd_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_linkfunctions7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
