# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lf7_scalar_probe <- function(name, eta, bounds) {
    .Call(`_linkfunctions7_lf7_scalar_probe`, name, eta, bounds)
}

lk_logit_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_logit_inv_cpp`, eta, k)
}

lk_logistic_poly_cpp <- function(p, k) {
    .Call(`_linkfunctions7_lk_logistic_poly_cpp`, p, k)
}

lk_logit_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_logit_fwd_cpp`, theta, k)
}

lk_probit_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_probit_fwd_cpp`, theta, k)
}

lk_probit_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_probit_inv_cpp`, eta, k)
}

lk_cloglog_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_cloglog_fwd_cpp`, theta, k)
}

lk_cloglog_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_cloglog_inv_cpp`, eta, k)
}

lk_loglog_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_loglog_fwd_cpp`, theta, k)
}

lk_loglog_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_loglog_inv_cpp`, eta, k)
}

lk_cauchit_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_cauchit_fwd_cpp`, theta, k)
}

lk_cauchit_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_cauchit_inv_cpp`, eta, k)
}

lk_rhobit_fwd_cpp <- function(theta, k) {
    .Call(`_linkfunctions7_lk_rhobit_fwd_cpp`, theta, k)
}

lk_rhobit_inv_cpp <- function(eta, k) {
    .Call(`_linkfunctions7_lk_rhobit_inv_cpp`, eta, k)
}

lk_softplus_fwd_cpp <- function(theta, a, k) {
    .Call(`_linkfunctions7_lk_softplus_fwd_cpp`, theta, a, k)
}

